num1=int(input("enter first number :"))
num2=int(input("enter second number :"))
add=num1+num2   
sub=num1-num2
mul=num1*num2
div=num1/num2
print("addition of two numbers=",add)
print("subtraction of two numbers=",sub)
print("multiplication of two numbers=",mul)     
print("division of two numbers=",div)